/*
File:         main.c
Purpose:      Calls the run_analysis function in tide_analyzer
Author:			  Lachlan Reynolds
Student #s:		14511638
CS Accounts:	a1a1 and b2b2
Date:			September 14, 2022
*/

/******************************************************************
DO NOT EDIT THIS FILE
******************************************************************/

/* Preprocessor directives */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "tide_analyzer.h"
#include "discrete_fourier_transform.h"

/*
Main function drives the program.
PRE:       NULL (no pre-conditions)
POST:      NULL (no side-effects)
RETURN:    IF the program exits correctly THEN 0 ELSE 1
*/


int main(void)
{
	printf("working\n");
	system("pause");
  return 0;
}